// Order action-types
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_FAV_BY_NAME = "ORDER_FAV_BY_NAME";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";


// Paginate action-types
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

// Favorite action-types
export const RESET_ALL_FAVORITES = "RESET_ALL_FAVORITES";
export const ORDER_FAV_BY_PRICE = "ORDER_FAV_BY_PRICE";
export const GET_FAVORITE_BY_NAME = "GET_FAVORITE_BY_NAME";
export const POST_FAVORITE = "POST_FAVORITE";
export const GET_FAVORITES = "GET_FAVORITES";
export const FIND_FAV_BY_NAME = "FIND_FAV_BY_NAME";
export const DELETE_FAV_BY_ID_BD="DELETE_FAV_BY_ID_BD"

// User action-types
export const ORDER_USER_BY_NAME = "ORDER_USER_BY_NAME";
export const ORDER_USER_BY_ROLE = "ORDER_USER_BY_ROLE";
export const ORDER_USER_BY_STATUS = "ORDER_USER_BY_STATUS";
export const GET_ALL_USER = "GET_ALL_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_NAME = "GET_USER_BY_NAME";
export const GET_USER_BY_ROL = "GET_USER_BY_ROL";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FROM_EDIT = "UPDATE_USER_FROM_EDIT";
export const POST_USER = "POST_USER";
export const GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL";
export const SEARCH_USERS = "SEARCH_USERS";

// Product action-types
export const POST_PRODUCT = "POST_PRODUCT";
export const UPDATE_PRODUCT_BY_ID = "UPDATE_PRODUCT_BY_ID";
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT ";
export const GET_PRODUCT_TRENDING = "GET_PRODUCT_TRENDING ";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const RESET_ALL_PRODUCT = "RESET_ALL_PRODUCT ";
export const GET_PRODUCT_CART = "GET_PRODUCT_CART";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const POST_PRODUCT_CART = "POST_PRODUCT_CART";
export const UPDATE_PRODUCT_CART = "UPDATE_PRODUCT_CART";

// Category action-types
export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_FROM_EDIT = "UPDATE_CATEGORY_FROM_EDIT";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GET_CATEGORIES_SHOP = "GET_CATEGORIES_SHOP";
export const GET_CATEGORIES_BY_ID = "GET_CATEGORIES_BY_ID";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_FAV__CATEGORY = "FILTER_FAV__CATEGORY";
export const ORDER_CATEGORY = "ORDER_CATEGORY";

// Order action-types
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";

