export const POST_PRODUCT = "POST_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT ";
export const GET_PRODUCT_BY_SEARCHBAR = "GET_PRODUCT_BY_SEARCHBAR";
export const GET_CATEGORIES = "GET_CATEGORIES";
